#!/bin/bash
PACKAGE_NAME="$DPKG_MAINTSCRIPT_PACKAGE"


systemctl stop $PACKAGE_NAME-auto-upgrade
systemctl disable $PACKAGE_NAME-auto-upgrade




if [ "$1" = "remove" ] || [ "$1" = "purge" ];then

echo "清理卸载残留"

rm -rf "/opt/apps/$PACKAGE_NAME"
else
echo "非卸载，跳过清理"
fi



